### ISSUE TITLE
Explorer is automatically switching to https when running in local environment

### ISSUE THREAD

**Issue by muthusleuths** [hirosystems/explorer#1786]
**Description**
Explorer is not allowing using http URL for API. When running in local network (for example Umbrel) API is not available over https. This worked fine in the past and now something seems to have changed where by default the connection is attempted over https and then throws an error.

**To Reproduce**
1. Go to Explorer
2. Click on network dropdown
3. Click on "Add Network"
4. Enter "http://umbrel.local:3999" as the API URL
5. See following error "Could not connect to supplied network URL."

**Expected behavior**
The umbrel.local network is added and selected as the API endpoint.

**Screenshots**
<img width="1618" alt="Screen Shot 2024-09-02 at 11 24 26 PM" src="https://github.com/user-attachments/assets/d870e50e-0045-4858-a3d3-15d8e0032462">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Additional context**
Running this umbrel project: https://github.com/muthusleuths/stacks-on-umbrel and it pulls the docker image with "latest" tag from https://hub.docker.com/r/hirosystems/explorer/tags which is currently v1.203

**Comment by muthusleuths** [comment]
@BLuEScioN  I am still facing the same error. As you can see from the screenshot my local API runs on my umbrel device and the URL I use to connect is http://umbrel.local:3999 

Does the fix you have in place only work for http://localhost:3999 ?

**Comment by muthusleuths** [comment]
This is from today after running explorer version 1.204.0 on my Umbrel Home
<img width="1622" alt="Screen Shot 2024-09-06 at 12 37 39 PM" src="https://github.com/user-attachments/assets/f23d227e-3642-4d8f-814c-e9463ca31550">

**Comment by muthusleuths** [comment]
@BLuEScioN Can you please take a look at this again. I think the issue is in the code you are looking for the URL to be "localhost" to not force TLS. If you see my screenshots you can see I am connecting to the API in "umbrel.local" endpoint. Not sure if there is an alternate approach we can use here. Perhaps look to pattern match on "local" instead of "localhost" ?

**Comment by BLuEScioN** [comment]
@muthusleuths Can you try again. The fix has been deployed.

**Comment by muthusleuths** [comment]
@BLuEScioN  please see this video to see how this is still half broken. When I set the environment variable for `NEXT_PUBLIC_MAINNET_API_SERVER` to `http://umbrel.local:3999` it still does not allow adding that URL and defaults to `https://api.hiro.so` instead. 

https://x.com/muthusleuths/status/1853953319309369730

**Comment by BLuEScioN** [comment]
@muthusleuths 

I have verified that this is working. Are you sure you are setting the nextjs env var correctly?

Also, not sure when that video was made, but I noticed in your video that you are not running the latest version of explorer. 

https://www.loom.com/share/8fe0562016c2451ab4c20e14ddc62e84?sid=67f9d67b-e124-4e94-9118-fef610853534
